### ISSUE TITLE
Projects no longer build in most recent version of Android Studio, Kotlin, and Gradle

### ISSUE THREAD

**Issue by benpva16** [davidgassner/AndroidDev2019FirstApp#1]
Projects do not build when pulling a branch fresh from the repo.

**Comment by Yemmm** [comment]
> Projects do not build when pulling a branch fresh from the repo.

I had this issue too and looked into it. To be more specific from the get-go, this is the issue I got:

"A problem occurred evaluating project ':app'. > Could not initialize class org.jetbrains.kotlin.gradle.plugin.sources.DefaultKotlinSourceSetKt"

The ext.kotlin_version is out of date. The kotlin version that is cloned is:

buildscript {
    ext.kotlin_version = '1.3.11'
    repositories {
        google()
        jcenter()
        
    }

Pressing shift twice to find it lead me to a dead end as Android Studio could not find it for some reason.

So if your issues were like mine, what I did was

1) Go to the file: Build.Gradle(Project: AndroidDev2019FirstApp). 
     a) Note that you will see a second build.gradle named build.gradle(Module: AndroidDev2019FirstApp). Ignore this one. This is 
        where Android Studio initially points the error you on line 3.

2) Click on the top left on File > Settings > Language and Framework > Kotlin
     a) You will see Current Kotlin plugin version. For me, I had 1.4.10-release-Studio4.1-1. What I took out of this was 1.4.10

3) Set the ext.kotlin_version to your version of kotlin, for me I used 1.4.10 since that is the version I had installed.
buildscript {
    ext.kotlin_version = '1.4.10'
    repositories {
        google()
        jcenter()
        
    }

4) Click on Sync on the top right after you changed it

I fixed it with the research from these two links:
https://stackoverflow.com/questions/60833542/kotlin-gradle-could-not-initialize-class-class-org-jetbrains-kotlin-gradle-inter
https://stackoverflow.com/questions/53682098/how-to-find-out-the-latest-version-of-kotlin-in-android-studio

**Comment by davidgassner** [comment]
@Yemmm, thank you for posting the steps for updating the project for the current versions of the software!

This is an unavoidable requirement due to the frequency of updates to Android Studio and the Kotlin plug-in. You could install the older versions of the software that I used when creating the course, but if you want to work through the course with the most recent releases these changes will be required.

**Comment by ayman-ibrahim** [comment]
@davidgassner 
Why you are not updating the project constantly as this is a beginner course and the course is already paid !

**Comment by davidgassner** [comment]
@ayman-ibrahim I wish we had time to do that. In this case, we have a new version of the course planned for the near future (I can't promise a specific date) that will work with new versions of Android Studio and will use Google's most recent recommendations for development best practices.
